version: 2.1

filters_always: &filters_always
  filters:
    tags:
      only: /.*/

filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

orbs:
  ruby: circleci/ruby@2.1.1
  bats: circleci/bats@1.0.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7 # TODO: matrix the supported ruby versions
    steps:
      - checkout
      - ruby/install-deps
      - run: make test

  smoke_test:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - bats/install
      - run:
          name: What's the BATS?
          command: |
            which bats
            bats --version
      - run:
          name: Smoke Test
          command: make smoke
      - store_test_results:
          path: ./smoke-tests/
      - store_artifacts:
          path: ./smoke-tests/report.xml
      - store_artifacts:
          path: ./smoke-tests/collector/data-results
      - run:
          name: Extinguish the flames
          command: make unsmoke

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - smoke_test

  build:
    jobs:
      - test:
          <<: *filters_always
      - smoke_test:
          <<: *filters_always
          requires:
            - test

