# frozen_string_literal: true

source "https://rubygems.org"

gem "honeycomb-opentelemetry", path: "../.."
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-sinatra"
gem "opentelemetry-sdk"
gem "rackup"
gem "sinatra"
